DEEPSORT:
  REID_CKPT: "./deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.4  # 0.2
  MIN_CONFIDENCE: 0.58  # yolov5s6 0.58, yolov5x6 0.7
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 16  # 70
  N_INIT: 8
  NN_BUDGET: 100
  